### ISSUE TITLE
リモートブーストやfavを行った場合、アイコンが点灯しない

### ISSUE THREAD

**Issue by denneko223355** [naumanni/naumanni#11]
・例
clubアカウントでclubのトゥートをブースト（fav）→点灯
clubアカウントでpawooのトゥート（非フォロー）をブースト（fav）→点灯せず
clubアカウントでpawooのトゥート（フォロワー）をブースト（fav）→点灯せず
clubアカウントでclubのユーザーがブーストしたpawooのトゥート（非フォロー）をブースト（fav）→点灯せず

club鯖以外でも発生したため、再現性はあると思われます。
最新版を自鯖に入れています。

2017/05/18追記
点灯しないもののブーストやfavは反映されています
また、Federated timelineでは正常に動いたのでUnited系が怪しいのかなと思います。

**Comment by shnjp** [comment]
調べてみます。

**Comment by denneko223355** [comment]
Consoleのlogを出せばよかったというのを#22 を見て気付かされる。

・fav1回目
POST https://mstdn.club/api/v1/statuses/929075/favourite 422 (Unprocessable Entity)
(anonymous) @ VM47:1
Request._end @ client.js:802
Request.end @ client.js:706
(anonymous) @ request-base.js:194
then @ request-base.js:193
client.js:423 Uncaught (in promise) Error: Unprocessable Entity
    at RetriableRequest.<anonymous> (client.js:423)
    at RetriableRequest.Emitter.emit (index.js:133)
    at XMLHttpRequest.xhr.onreadystatechange (client.js:735)
(anonymous) @ client.js:423
Emitter.emit @ index.js:133
xhr.onreadystatechange @ client.js:735

・fav2回め
client.js:423 Uncaught (in promise) Error: Unprocessable Entity
    at RetriableRequest.<anonymous> (client.js:423)
    at RetriableRequest.Emitter.emit (index.js:133)
    at XMLHttpRequest.xhr.onreadystatechange (client.js:735)
(anonymous) @ client.js:423
Emitter.emit @ index.js:133
xhr.onreadystatechange @ client.js:735
