### ISSUE TITLE
Build Error: Can't resolve naumanniConfig and naumanniPlugins

### ISSUE THREAD

**Issue by noraworld** [naumanni/naumanni#128]
The errors occur while running `yarn run build`.

The error messages are the following.

```
WARNING in ./src/js/config.es6
Module not found: Error: Can't resolve 'naumanniConfig' in '/home/vagrant/naumanni/src/js'
 @ ./src/js/config.es6 18:17-42
 @ ./src/js/pages/Dashboard.es6
 @ ./src/js/main.es6
 @ multi babel-polyfill ./src/js/main.es6

ERROR in ./src/js/pages/Dashboard.es6
Module not found: Error: Can't resolve 'naumanniPlugins' in '/home/vagrant/naumanni/src/js/pages'
 @ ./src/js/pages/Dashboard.es6 116:36-62 385:37-63
 @ ./src/js/main.es6
 @ multi babel-polyfill ./src/js/main.es6

ERROR in ./src/js/usecases/InitializeApplicationUseCase.es6
Module not found: Error: Can't resolve 'naumanniPlugins' in '/home/vagrant/naumanni/src/js/usecases'
 @ ./src/js/usecases/InitializeApplicationUseCase.es6 104:37-63
 @ ./src/js/pages/Dashboard.es6
 @ ./src/js/main.es6
 @ multi babel-polyfill ./src/js/main.es6
```

According to above, the reason why errors occur is because `src/js/naumanniConfig`, `src/js/pages/naumanniPlugins` and `src/js/usecases/naumanniPlugins` are not found. These are not created by running `yarn`, and also not found in this repository.

How should it be fixed?

* Node.js v7.5.0
* Yarn 0.23.4
* Tree [a73e7f6f49](https://github.com/naumanni/naumanni/tree/a73e7f6f492febddc0f4305e93c232d96ea54dbc)

**Comment by Neustrashimy** [comment]
Create empty `plugin_entries.css` file on Naumanni directory and try again, please?

**Comment by noraworld** [comment]
I created empty `plugin_entries.css` file in Naumanni directory, then run `yarn run build`. But the same errors still occur.

**Comment by Neustrashimy** [comment]
Copy `plugin_entries.ci.es6`  and rename to `plugin_entries.es6`, and try again.
(if you have `plugin_entries.es6` then ignore me)

**Comment by noraworld** [comment]
I copied `plugin_entries.ci.es6` and renamed it `plugin_entries.es6`. Then errors cloud be fixed. But new error happened.

```
$ postcss src/css/main.css -d static 
✖ Finished src/css/main.css (406ms)

undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
25:1	⚠  /home/vagrant/naumanni/plugin_entries.css is empty [postcss-import]
```

This error occurs because empty `plugin_entries.css` file was created before, but a problem is not resolved.

**Comment by Neustrashimy** [comment]
Those warning is displayed in my environment too. but, build was successful.
You can proceed to the next step. (docker build, etc)

**Comment by noraworld** [comment]
So I cloud build and the web service works fine for now. Thank you for your help. But I still have 3 questions.

1. No errors occur thanks to your advice, but the following warning still happen to me. Is this OK?
```
WARNING in ./src/js/config.es6
Module not found: Error: Can't resolve 'naumanniConfig' in '/home/vagrant/naumanni/src/js'
 @ ./src/js/config.es6 18:17-42
 @ ./src/js/pages/Dashboard.es6
 @ ./src/js/main.es6
 @ multi babel-polyfill ./src/js/main.es6
```

2. When a user that has not visited the Naumanni website even once before visits there, he or she should be redirected to the welcome page (`/welcome`) according to the flagship website [naumanni.com](https://naumanni.com). But the welcome page is not shown on my environment. Why is it? By the way, my environment is on non-Docker, not on Docker.

3. I think what we should create empty `plugin_entries.css` file and copy `plugin_entries.ci.es6` to `plugin_entries.cs6` must be fixed in this repository. Is this a bug with a build, or do we miss something to do?

**Comment by Neustrashimy** [comment]
1 and 2: 
Do you have `config.es6` in Naumanni directory?
If you not, copy `config.es6.in` and rename to `config.es6`, and edit it.
Then, rebuild Naumanni again. 

3: We need assistance from dev team.

**Comment by noraworld** [comment]
I copied `config.es6.in`, renamed it to `config.es6`, and edited it to my own environment. After that, I rebuilt the Naumanni again, then that warning doesn't happen, but the welcome page is still not shown.

**Comment by Neustrashimy** [comment]
Did you confirm that `Can't resolve 'naumanniConfig'` error was resolved by creating `config.es6` ?
then, try "reset all".

settings -> emergency -> reset all

![capture](https://user-images.githubusercontent.com/22212225/30420266-fe6156c6-9973-11e7-9f71-3b03d17c2ced.JPG)

This action will remove all local storage data, so you will return to "when you first visited".

**Comment by noraworld** [comment]
I tried to clear all session of the Naumanni website, and visited again. Then my customized welcome page appeared!

Many thanks to your help, @Neustrashimy. I hope to improve the Naumanni documentation (README) to be added that `plugin_entries.css`, `plugin_entries.es6` and `config.es6` should be created before building the Naumanni :D
