### ISSUE TITLE
Cmd+Enterで投稿したい

### ISSUE THREAD

**Issue by rinsuki** [naumanni/naumanni#13]
(Mac)Cmdキー==(Win)Windowsキー==(JavaScriptでの判定)`metaKey`

**Comment by shnjp** [comment]
本家同様 Ctrl+Enter で投稿できますが、どうでしょうか？

**Comment by rawegg** [comment]
本家はCmd+Enterでも投稿できますね。

**Comment by rinsuki** [comment]
キー的にLinux/WindowsでのCtrlをCmdにしてるのと、他のSNS(青い鳥、mastodonのWeb、GitHub、etc...)でCmd+Enterに慣れてしまってるので、Cmd+Enterで投稿できるとありがたいです
