### ISSUE TITLE
[Question] API サーバーについて

### ISSUE THREAD

**Issue by ghost** [naumanni/naumanni#16]
[ここ](https://github.com/naumanni/naumanni/blob/55d0512674b63f84fa8523b446c8c3f3b174dd63/etc/docker/nginx/naumanni.conf#L27-L29) で指定してる API サーバーとはなんですか？

**Comment by shnjp** [comment]
ｵｯ

@shi3z が言っているところの、AI判定や、リンクのOGP情報やらの返答やら、ブラウザ側で出来ない事をよる予定のサーバです。
まだありません…

**Comment by ghost** [comment]
わかりました。ありがとうございます！
