### ISSUE TITLE
Notification欄に横スクロールバーが出る

### ISSUE THREAD

**Issue by Neustrashimy** [naumanni/naumanni#33]
alpha-0.1.2-14-g0555e3d

ユーザー名が長いと出る可能性があります。

![075e4a1946635edd](https://cloud.githubusercontent.com/assets/22212225/26284851/8012d6cc-3e7f-11e7-8436-5497f2e33635.png)

**Comment by shnjp** [comment]
なるほど！　再現できなくて困っていました。
ありがとうございます。
