### ISSUE TITLE
Nginx SSL対応

### ISSUE THREAD

**Issue by Neustrashimy** [naumanni/naumanni#51]

**Comment by ghost** [comment]
@Neustrashimy SSL対応とはどの環境のことを指してるのですか?

**Comment by Neustrashimy** [comment]
Docker内のNginxでSSL対応できないかなと思っていました。
そもそも、そういう使い方ではなかったのですね。。。

結果的に、Docker外にリバースプロキシを設置し、SSL対応できました。
お騒がせしました。

**Comment by shnjp** [comment]
そうですね。個々のアプリケーションサーバ側に証明書入れると面倒なので外側で解決するのが良いと思います。
http/2とか考えだしたらまた違うと思うけど。

**Comment by ghost** [comment]
私はnaumanniをDockerで試すのはローカル環境でのためだと思っています。
NaumanniでDockerを使うとしたらビルドする工程をDockerを使えばいいと思いますよ。

> Docker外にリバースプロキシを設置し...

そんなことをしなくても

```console
cp ./www ./public
cp ./static ./public/static
```

したあとに `./public` ディレクトリを Nginxのrootに指定したらいいと思いますよ

> http/2

Nginx の場合はOpenSSLなど場を整えてあげると使えるようになりますし簡単に使いたいのであればH2Oを使ったらいいと思います。

**Comment by Neustrashimy** [comment]
ファイルをコピるだけで動くならとっても助かります。試してみます。

**Comment by Neustrashimy** [comment]
@39e ご教示頂いた方法で動作しました！ ありがとうございます。
