### ISSUE TITLE
[要望] 公開鍵について

### ISSUE THREAD

**Issue by ghost** [naumanni/naumanni#88]
公開鍵がプロフィールに書かれますが現在
`PGP Key Fingerprint: <40桁の英数字>`
となっており、160文字使えるうちの約60文字が使えなくなるので `PGP Key Fingerprint` の部分を短縮できませんでしょうか？

**Comment by shnjp** [comment]
はい、よく考えるとProfileは最新のものが常に得られるとは限らないのでこの機能は削除します…
